const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
require('node:fs').mkdirSync(path.resolve(__dirname,'screenshots'),{recursive:true});
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:393,height:852},deviceScaleFactor:2});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file://'+path.resolve(__dirname,'../app/src/main/assets/index.html'));
 await page.evaluate(()=>{window.calls=[];window.Native=new Proxy({},{get:(_,method)=>(...args)=>calls.push({method,args})});});
 await page.screenshot({path:path.resolve(__dirname,'screenshots/welcome.png')});
 await page.getByRole('button',{name:'Explore first'}).click();
 assert.equal(await page.locator('#welcome').evaluate(e=>e.classList.contains('open')),false);
 await page.screenshot({path:path.resolve(__dirname,'screenshots/empty-library.png')});
 const tracks=[{id:'1',title:'Morning light',artist:'Test artist',album:'Test album',duration:180000},{id:'2',title:'Evening waves',artist:'Another artist',album:'Second album',duration:240000},{id:'3',title:'<script>alert(1)</script>',artist:'Safe text',album:'Test album',duration:60000}];
 await page.evaluate(t=>receive('library',{tracks:t,permission:true}),tracks);
 assert.equal(await page.locator('#library .song').count(),3);
 await page.locator('#search').fill('morning');assert.equal(await page.locator('#library .song').count(),1);
 await page.locator('#library .songMain').click();assert.equal(await page.evaluate(()=>calls.at(-1).method),'play');
 await page.locator('#library .heart').click();await page.locator('#search').fill('');
 await page.getByRole('button',{name:'Favorites',exact:true}).click();assert.equal(await page.locator('#library .song').count(),1);
 await page.getByRole('button',{name:'Albums',exact:true}).click();assert.equal(await page.locator('.album').count(),2);
 await page.locator('[data-album="Test album"]').click();assert.equal(await page.locator('#library .song').count(),2);
 await page.evaluate(t=>{setTab('songs');receive('playback',{track:t[0],queue:t,playing:true,position:50000,duration:180000,shuffle:false,repeat:0,error:''})},tracks);
 await page.screenshot({path:path.resolve(__dirname,'screenshots/library-with-test-tracks.png')});
 await page.locator('#mini .songMain').click();assert.equal(await page.locator('#playerTitle').textContent(),'Morning light');
 await page.locator('#shuffle').click();assert.deepEqual(await page.evaluate(()=>calls.at(-1)),{method:'command',args:['shuffle',0]});
 await page.locator('#repeat').click();assert.deepEqual(await page.evaluate(()=>calls.at(-1)),{method:'command',args:['repeat',0]});
 await page.screenshot({path:path.resolve(__dirname,'screenshots/player.png')});
 await page.locator('#player [aria-label="Open queue"]').click();assert.equal(await page.locator('#queueList .song').count(),3);
 await page.evaluate(()=>handleBack());await page.evaluate(()=>handleBack());
 await page.getByRole('button',{name:'Account and settings'}).click();
 await page.getByRole('button',{name:'Sign in with Google',exact:true}).click();assert.equal(await page.evaluate(()=>calls.at(-1).method),'signIn');
 await page.getByRole('button',{name:'Allow music access',exact:true}).click();assert.equal(await page.evaluate(()=>calls.at(-1).method),'permission');
 await page.getByRole('button',{name:'Import audio files',exact:true}).last().click();assert.equal(await page.evaluate(()=>calls.at(-1).method),'pick');
 for(const width of [320,393,600]){await page.setViewportSize({width,height:740});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)}
 assert.deepEqual(errors,[]);console.log('PASS: onboarding, metadata escaping, search, favorites, albums, playback dispatch, shuffle, repeat, queue, sign-in/permission/import dispatch, 320/393/600px widths; no JavaScript errors.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
